language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="12.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  - EXCLUDE=l10n_fr_chorus_facturx,l10n_fr_chorus_ubl,l10n_fr_business_document_import,l10n_fr_chorus_account,l10n_fr_fec_oca,l10n_fr_chorus_sale
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  # what we have here is not compatible with Odoo's account_facturx which is autoinstall
  - rm -fr ${HOME}/{odoo,OCB}-12.0/addons/account_facturx
  - pip install unicodecsv unidecode ofxparse PyPDF2 factur-x

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
